; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	D:\code\qt\MyPeTools\MyPeTools\Debug\moc\moc_mypetools.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG214036 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
$SG214037 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214038 DB	'qRegisterNormalizedMetaType', 00H
$SG212285 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG212286 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212287 DB	'qRegisterNormalizedMetaType', 00H
$SG214338 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG214339 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214340 DB	'qRegisterNormalizedMetaType', 00H
$SG215490 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG215491 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG215492 DB	'qRegisterNormalizedMetaType', 00H
$SG212587 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG212588 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212589 DB	'qRegisterNormalizedMetaType', 00H
$SG214728 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG214729 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214730 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_MyPeTools@@3Uqt_meta_stringdata_MyPeTools_t@@B DD 0ffffffffH ; qt_meta_stringdata_MyPeTools
	DD	09H
	DD	00H
	DD	050H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	DD	04aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	045H
	DD	0ffffffffH
	DD	010H
	DD	00H
	DD	036H
	DD	0ffffffffH
	DD	010H
	DD	00H
	DD	037H
	DB	'MyPeTools', 00H, 'slot_start', 00H, 00H, 'slot_SetWidegt'
	DB	'Ui', 00H, 'QTreeWidgetItem*', 00H
$SG213734 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
$SG213735 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213736 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_MyPeTools@@3QBIB DD 07H			; qt_meta_data_MyPeTools
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	0aH
	DD	03H
	DD	02H
	DD	019H
	DD	02H
	DD	0aH
	DD	02bH
	DD	02bH
	DD	080000004H
	DD	02H
	DD	02H
	DD	02H
	DD	00H
$SG212889 DB	'D:\Qt\Qt5.9.8\5.9.8\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG212890 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212891 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@MyPeTools@@UBEPBUQMetaObject@@XZ	; MyPeTools::metaObject
PUBLIC	?qt_metacast@MyPeTools@@UAEPAXPBD@Z		; MyPeTools::qt_metacast
PUBLIC	?qt_metacall@MyPeTools@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; MyPeTools::qt_metacall
PUBLIC	?qt_static_metacall@MyPeTools@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MyPeTools::qt_static_metacall
PUBLIC	?staticMetaObject@MyPeTools@@2UQMetaObject@@B	; MyPeTools::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?slot_start@MyPeTools@@QAEXXZ:PROC		; MyPeTools::slot_start
EXTRN	?slot_SetWidegtUi@MyPeTools@@QAEXPAVQTreeWidgetItem@@H@Z:PROC ; MyPeTools::slot_SetWidegtUi
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@MyPeTools@@2UQMetaObject@@B DB 018H DUP (?) ; MyPeTools::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@MyPeTools@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@MyPeTools@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@MyPeTools@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@MyPeTools@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@MyPeTools@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'MyPeTools::staticMetaObject'', COMDAT
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 86
	push	ebp
	mov	ebp, esp
; Line 84
	mov	eax, DWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B, eax
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_MyPeTools@@3Uqt_meta_stringdata_MyPeTools_t@@B
; Line 85
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_MyPeTools@@3QBIB
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@MyPeTools@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MyPeTools::qt_static_metacall
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B+16, 0
	mov	DWORD PTR ?staticMetaObject@MyPeTools@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@MyPeTools@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'MyPeTools::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__t$1 = -8						; size = 4
tv69 = -4						; size = 4
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@MyPeTools@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; MyPeTools::qt_static_metacall
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 71
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 72
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN1@qt_static_
; Line 73
	mov	eax, DWORD PTR __o$[ebp]
	mov	DWORD PTR __t$1[ebp], eax
; Line 75
	mov	ecx, DWORD PTR __id$[ebp]
	mov	DWORD PTR tv69[ebp], ecx
	cmp	DWORD PTR tv69[ebp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[ebp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN1@qt_static_
$LN5@qt_static_:
; Line 76
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?slot_start@MyPeTools@@QAEXXZ		; MyPeTools::slot_start
	jmp	SHORT $LN1@qt_static_
$LN6@qt_static_:
; Line 77
	mov	edx, 4
	shl	edx, 1
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	eax, DWORD PTR [edx]
	push	eax
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?slot_SetWidegtUi@MyPeTools@@QAEXPAVQTreeWidgetItem@@H@Z ; MyPeTools::slot_SetWidegtUi
$LN1@qt_static_:
; Line 81
	mov	esp, ebp
	pop	ebp
	ret	0
?qt_static_metacall@MyPeTools@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; MyPeTools::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@MyPeTools@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; MyPeTools::qt_metacall
; _this$ = ecx
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 103
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 104
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 105
	cmp	DWORD PTR __id$[ebp], 0
	jge	SHORT $LN2@qt_metacal
; Line 106
	mov	eax, DWORD PTR __id$[ebp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 107
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN3@qt_metacal
; Line 108
	cmp	DWORD PTR __id$[ebp], 2
	jge	SHORT $LN5@qt_metacal
; Line 109
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	?qt_static_metacall@MyPeTools@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; MyPeTools::qt_static_metacall
	add	esp, 16					; 00000010H
$LN5@qt_metacal:
; Line 110
	mov	ecx, DWORD PTR __id$[ebp]
	sub	ecx, 2
	mov	DWORD PTR __id$[ebp], ecx
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 111
	cmp	DWORD PTR __c$[ebp], 12			; 0000000cH
	jne	SHORT $LN4@qt_metacal
; Line 112
	cmp	DWORD PTR __id$[ebp], 2
	jge	SHORT $LN7@qt_metacal
; Line 113
	mov	edx, 4
	imul	eax, edx, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	DWORD PTR [edx], -1
$LN7@qt_metacal:
; Line 114
	mov	eax, DWORD PTR __id$[ebp]
	sub	eax, 2
	mov	DWORD PTR __id$[ebp], eax
$LN4@qt_metacal:
; Line 116
	mov	eax, DWORD PTR __id$[ebp]
$LN1@qt_metacal:
; Line 117
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@MyPeTools@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; MyPeTools::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@MyPeTools@@UAEPAXPBD@Z PROC		; MyPeTools::qt_metacast
; _this$ = ecx
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 95
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 96
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 97
	push	OFFSET ?qt_meta_stringdata_MyPeTools@@3Uqt_meta_stringdata_MyPeTools_t@@B+80
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 98
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 99
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 100
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@MyPeTools@@UAEPAXPBD@Z ENDP		; MyPeTools::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@MyPeTools@@UBEPBUQMetaObject@@XZ PROC	; MyPeTools::metaObject
; _this$ = ecx
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 90
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 91
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@MyPeTools@@2UQMetaObject@@B ; MyPeTools::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 92
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@MyPeTools@@UBEPBUQMetaObject@@XZ ENDP	; MyPeTools::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File d:\qt\qt5.9.8\5.9.8\msvc2015\include\qtcore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 120
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\code\qt\mypetools\mypetools\debug\moc\moc_mypetools.cpp
; Line 120
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
